# Theme:       awøken⸸vails
#               øggtíøns▽mnlth43

font_family      Sarasa Mono T Extralight
bold_font        Sarasa Mono T Light
italic_font      auto
bold_italic_font auto
font_size        12.5
text_composition_strategy legacy

hide_window_decorations yes
confirm_os_window_close 0
window_padding_width  8

background            #140824
foreground            #f8f8f2
background_opacity    1.0

# --- KEYBINDINGS ---
map super+c copy_to_clipboard
map super+v paste_from_clipboard

# --- TERMINAL PALETTE (ANSI) ---
color0  #140824
color8  #321556
color1  #4F2683
color9  #6f3ba8
color2  #2ed07e
color10 #53ea9d
color3  #FFC62F
color11 #ffd359
color4  #4F2683
color12 #6f3ba8
color5  #894ba0
color13 #bc7fd3
color6  #FFC62F
color14 #ffd359
color7  #a29bb0
color15 #f8f8f2
