# Theme: awøken⸸vails
#         øggtíøns▽mnlth43 

# Layout & Rahmen Einstellungen
general {
    gaps_in = 4
    gaps_out = 6
    border_size = 2

    # Aktiv: Gold startet oben links und verläuft nach unten rechts in dein Vikings-Lila
    col.active_border = rgba(FFC62Fff) rgba(4F2683ff) 45deg
    
    # Inaktiv: Genau umgedreht – Lila startet oben links, das kräftige Gold sitzt unten rechts
    col.inactive_border = rgba(4F2683ff) rgba(FFC62Fff) 45deg

    layout = scrolling
}

# Glas-Optik, Transparenz & Schatten für das ganze System
decoration {
    rounding = 5

    # Adaptiver Glas-Shader (Screen-Shader für das gesamte Rendering)
    screen_shader = ~/.config/hypr/shaders/dynamic_glass.frag

    # Systemweite Transparenz (Aktiv / Inaktiv)
    active_opacity = 0.75
    inactive_opacity = 0.50

    # Systemweiter Blur (holt den transparenten Glas-Effekt zurück)
    blur {
        enabled = true
        size = 1
        passes = 1
        ignore_opacity = false
        new_optimizations = true
        xray = false
    }

    # Dein lila Schatten / Glow-Effekt
    shadow {
        enabled = true
        range = 3            # Wie weit das lila Leuchten nach außen strahlt
        render_power = 4     # Wie knackig der Schatten verläuft
        
        # Aktiv: Dein kräftiges Vikings-Lila
        color = rgba(FFC62Faa)
        
        # Inaktiv: Ein ganz dunkler, matter Schatten
        color_inactive = rgba(4F2683aa)
    }
}

# Animationen (geschmeidig für den Rahmen-Wechsel)
animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    animation = windows, 1, 7, myBezier
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}

