# Theme: awøken⸸vails
# øggtíøns▽mnlth43

general {
    gaps_in = 6
    gaps_out = 8
    border_size = 2

    col.active_border = rgba(FFC62Fff) rgba(4F2683ff) 45deg
    col.inactive_border = rgba(4F2683ff) rgba(FFC62Fff) 180deg

    layout = dwindle
}

decoration {
    rounding = 5

    # Globaler Shader (Stand Anfang des Chats)
    screen_shader = /home/kupfi/.config/hypr/shaders/dynamic_glass.frag

    active_opacity = 0.9
    inactive_opacity = 0.68

    blur {
        enabled = false
        size = 1
        passes = 1
        ignore_opacity = false
        new_optimizations = true
        xray = false
    }

    shadow {
        enabled = true
        range = 1
        render_power = 1
        color = rgba(FFC62Faa)
        color_inactive = rgba(4F2683aa)
    }
}

animations {
    enabled = yes
    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = border, 1, 10, default
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default
}
