# 1. Globale Wildcard deaktiviert lassen
# monitor=,preferred,auto,auto

# 2. INTERN: Razer Blade OLED (Liegt links auf Position 0x0 mit Skalierung 1.6)
monitor = eDP-1, 2560x1600@240.00Hz, 0x0, 1.60

# Fallback, falls sich der interne Port-Name dynamisch auf eDP-2 ändert
monitor = eDP-2, 2560x1600@240.00Hz, 0x0, 1.60

# 3. EXTERN: OMEN 24 (Liegt rechts ab Pixel 1600, nativ 1920x1080 @ 165Hz, Skalierung 1.0)
monitor = HDMI-A-1, 1920x1080@165.00Hz, 1600x0, 1.00

# 3. EXTERN: OMEN 24 (Hochkant / Portrait Mode, 1080x1920 @ 165Hz)
# monitor = HDMI-A-1, 1920x1080@165.00Hz, 1600x0, 1.00, transform, 1


# Option B: Nativ 1.0x (Falls du volle 4K-Arbeitsfläche ungepuffert brauchst)
# monitor = HDMI-A-1, 3840x2160@60.00Hz, 1600x0, 1.00

# Option auto tv 
# monitor = HDMI-A-1,preferred, auto, 1.00 
